# Библиотека NumPy Python для Data Science и Machine Learning

Конспект по библиотеке **NumPy** с акцентом на применение в DS и ML.


## 1. Введение в NumPy

**NumPy (Numerical Python)** — библиотека для научных вычислений в Python.

Почему NumPy важен для DS/ML:
- Быстрые вычисления (реализация на C)
- Эффективная работа с памятью
- Векторизация (без циклов)
- Основа для pandas, sklearn, TensorFlow, PyTorch


In [1]:
import numpy as np

## 2. Базовые математические функции

In [2]:
# Корни и модули
print(np.sqrt(16))      # квадратный корень
print(np.abs(-5))       # модуль
print(np.sign(-5))      # знак (-1, 0 1)
print()

# Логарифмы
print(np.log(10))      # натуральный логарифм
print(np.log10(10))
print(np.log2(10))
print()

# Экспонента
np.exp(10)
print()

# Полезные константы
print("Пи:", np.pi)
print("е:", np.e)

x = np.inf
y = np.nan

print(x)
print(-x)
print(y)

# проверки
print(np.isinf(x))
print(np.isnan(x))

4.0
5
-1

2.302585092994046
1.0
3.321928094887362


Пи: 3.141592653589793
е: 2.718281828459045
inf
-inf
nan
True
False


## 3. Массивы ndarray

Основной объект в NumPy — это ndarray (N-dimensional array), который:
- хранит элементы одного типа (в отличие от списков Python);
- имеет фиксированный размер (в отличие от динамических списков);
- поддерживает векторизацию (операции выполняются сразу на всем массиве, без циклов).

### Создание массивов

In [3]:
print("\n 1D массив:\n", np.array([1, 2, 3]))        # 1D массив (вектор)
print("\n 2D массив:\n", np.array([[1, 2, 3],       # 2D массив (матрица)
                     [4, 5, 6]]))
print("\n Нули:\n", np.zeros((3, 3)))           # матрица 3x3 из нулей
print("\n Единицы:\n", np.ones((2, 4)))            # матрица 2x4 из единиц
print("\n С шагом:\n", np.arange(0, 10, 2))        # числа от 0 до 8 с шагом 2
print("\n С шагом в диапазоне:\n", np.linspace(0, 1, 5))       # 5 чисел от 0 до 1
print("\n Единичная матрица:\n", np.eye(3))                  # единичная матрица 3x3
print("\n Матрица, заполненная 7:\n", np.full((2, 3), 7))         # матрица 2x3, заполненная 7

np.random.seed(42)             # не обязательно
print("\n Случайные числа:\n", np.random.rand(2, 3))       # случайные числа [0,1)
print("\n Нормально распределенные числа:\n", np.random.randn(2, 3))      # генерирует массив случайных чисел, распределенных по стандартному нормальному закону (распределение Гаусса)
                               # (mean): 0, (std): 1
print("\n Случайные целые:\n", np.random.randint(0, 10, (3, 3)))  # случайные целые 0–9

# choice используется для генерации случайной выборки из заданного одномерного массива или диапазона чисел
# часто используется для bootstrap.
a = [1, 2, 3]
print("\n choice:\n", np.random.choice(a, size=5))  


 1D массив:
 [1 2 3]

 2D массив:
 [[1 2 3]
 [4 5 6]]

 Нули:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 Единицы:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 С шагом:
 [0 2 4 6 8]

 С шагом в диапазоне:
 [0.   0.25 0.5  0.75 1.  ]

 Единичная матрица:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 Матрица, заполненная 7:
 [[7 7 7]
 [7 7 7]]

 Случайные числа:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]

 Нормально распределенные числа:
 [[ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]]

 Случайные целые:
 [[9 5 8]
 [0 9 2]
 [6 3 8]]

 choice:
 [3 1 3 3 1]


### Атрибуты массива
- shape — форма
- ndim — количество измерений
- dtype — тип данных
- size — количество элементов


In [4]:
a = np.array([[1,2,3],[4,5,6]])
print('a.shape =', a.shape)
print('a.ndim =', a.ndim)
print('a.dtype =', a.dtype)
print('a.size =', a.size)

a.shape = (2, 3)
a.ndim = 2
a.dtype = int32
a.size = 6


## 4. Основные операции

In [5]:
# поэлементные
x = np.array([1,2,3])
y = np.array([4,5,6])

print("x + y =", x + y)
print("x - y =", x - y)
print("x * y =", x * y)
print("x / y =", x / y)
print("x ** 2 =", x ** 2)

print("np.add =", np.add(x,y))            # аналог x + y
print("np.subtract =", np.subtract(x,y))  # аналог x - y
print("np.multiply =", np.multiply(x,y))  # аналог x * y
print("np.divide =", np.divide(x,y))      # аналог x / y
print("np.power =", np.power(x,2))        # аналог x ** 2

print("np.sum =", np.sum(x))                # сумма элементов массива
print("np.cumsum =", np.cumsum(x))          # кумулятивная сумма элементов массива


# индексация и срезы
arr = np.arange(10)

print() 
print(arr[0])        # первый элемент
print(arr[-1])       # последний элемент
print(arr[2:6])      # срез
print(arr[arr > 5])  # логическая индексация


# векторизация и Broadcasting
# Broadcasting позволяет выполнять операции над массивами разной формы без циклов

q = np.array([1,2,3])
print() 
print(q + 10)  # прибавление ко всем элементам

x + y = [5 7 9]
x - y = [-3 -3 -3]
x * y = [ 4 10 18]
x / y = [0.25 0.4  0.5 ]
x ** 2 = [1 4 9]
np.add = [5 7 9]
np.subtract = [-3 -3 -3]
np.multiply = [ 4 10 18]
np.divide = [0.25 0.4  0.5 ]
np.power = [1 4 9]
np.sum = 6
np.cumsum = [1 3 6]

0
9
[2 3 4 5]
[6 7 8 9]

[11 12 13]


## 5. Работа с формой массива

In [6]:
z = np.arange(6)

print(" z =", z)

z_mx = z.reshape(2,3)                         # переформатирование в другую форму
print("\n reshape 2x3:\n", z_mx)

print("\n flatten:", z_mx.flatten())          # переформатирование в вектор
print("\n transpose:\n", np.transpose(z_mx))  # транспонирование
print("\n transpose:\n", z_mx.T)              # то же самое

a1 = np.array([[1,2]])
a2 = np.array([[3,4]])
print("\n vstack:\n", np.vstack((a1,a2)))     # Соединяет таблицы одну под другой (по вертикали)
print("\n hstack:\n", np.hstack((a1.T,a2.T))) # Соединяет таблицы бок о бок (по горизонтали)

 z = [0 1 2 3 4 5]

 reshape 2x3:
 [[0 1 2]
 [3 4 5]]

 flatten: [0 1 2 3 4 5]

 transpose:
 [[0 3]
 [1 4]
 [2 5]]

 transpose:
 [[0 3]
 [1 4]
 [2 5]]

 vstack:
 [[1 2]
 [3 4]]

 hstack:
 [[1 3]
 [2 4]]


## 6. Логические операции

In [7]:
arr = np.array([1,5,7,9])

print("where >5:", np.where(arr > 5))  # индексы элементов, которые больше 5
print("all >0:", np.all(arr > 0))  # True, если ВСЕ элементы больше 0
print("any <0:", np.any(arr < 0))  # True, если ХОТЯ БЫ один элемент меньше 0
print("маска 3< arr <8:", arr[(arr>3) & (arr<8)])  # возвращает элементы, которые одновременно >3 и <8
print("np.clip:", np.clip(arr, 3, 7))  # ограничивает значения массива x диапазоном [min, max]

where >5: (array([2, 3], dtype=int64),)
all >0: True
any <0: False
маска 3< arr <8: [5 7]
np.clip: [3 5 7 7]


## 7. Векторная алгебра

В ML:
- объект = вектор признаков
- веса = вектор
- модель часто = скалярное произведениение


In [8]:
v1 = np.array([1,2,3])
v2 = np.array([2,4,6])
v3 = np.array([1,2,3])

print("Нулевой:", np.zeros(3))
print("Коллинеарные:", np.all(v2 == 2*v1))
print("Равные:", np.array_equal(v1,v3))

print("Сумма:", v1+v2)
print("Разность:", v2-v1)
print("Умножение на число:", 3*v1)
print("Линейная комбинация:", 2*v1 + 3*v2)

dot = np.dot(v1,v2)
print("Скалярное произведение:", dot)

length = np.linalg.norm(v1)
print("Длина вектора:", length)

cos = dot/(np.linalg.norm(v1)*np.linalg.norm(v2))
print("Cos угла:", cos)

cross = np.cross(v1,v2)
print("Векторное произведение:", cross)

v4 = np.array([1,0,1])
mixed = np.dot(v1, np.cross(v2,v4))
print("Смешанное произведение:", mixed)

Нулевой: [0. 0. 0.]
Коллинеарные: True
Равные: True
Сумма: [3 6 9]
Разность: [1 2 3]
Умножение на число: [3 6 9]
Линейная комбинация: [ 8 16 24]
Скалярное произведение: 28
Длина вектора: 3.7416573867739413
Cos угла: 1.0
Векторное произведение: [0 0 0]
Смешанное произведение: 0


## 8. Матрицы и линейная алгебра

В ML:
- датасет — матрица X (матрица векторов признаков)
- веса — вектор w
- модель — Xw

In [9]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("\n Квадратная:\n", A)
print("\n Единичная:\n", np.eye(2))
print("\n Диагональная:\n", np.diag([1,2,3]))
print("\n Нулевая:\n", np.zeros((2,2)))
print("\n Ранг:", np.linalg.matrix_rank(A))

print("\n Сложение:\n", A+B)
print("\n Умножение на число:\n", 2*A)
print("\n Перемножение матриц:\n", A@B)

print("\n Определитель:", np.linalg.det(A)) # Определитель матрицы (показывает вырождена ли матрица; если 0 — обратной нет)

minor = A[1:,1:]
print("\n Базисный минор:\n", minor)
print("\n det минора:", np.linalg.det(minor))

eigvals, eigvecs = np.linalg.eig(A)
print("\n Собственные векторы:\n", eigvecs) # Собственный вектор — это такой вектор, который при умножении на матрицу не меняет направление. Он может только растянуться или сжаться.
print("\n Собственные значения:", eigvals)  # А число, на которое он растягивается — это собственное значение.

print("\n Транспонирование:\n", A.T)
print("\n Обратная матрица:\n", np.linalg.inv(A))      # Обратная матрица (A^{-1}); существует только если det(A) ≠ 0

C = np.array([[1,2],[3,4],[5,6]])
 
print("\n SVD-разложение:\n", np.linalg.svd(A))           # SVD-разложение: A = U Σ V^T (используется в PCA и понижении размерности)
print("\n Псевдообратная матрица:\n", np.linalg.pinv(C))  # Псевдообратная матрица (работает даже если матрица вырожденная или прямоугольная)


 Квадратная:
 [[1 2]
 [3 4]]

 Единичная:
 [[1. 0.]
 [0. 1.]]

 Диагональная:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]

 Нулевая:
 [[0. 0.]
 [0. 0.]]

 Ранг: 2

 Сложение:
 [[ 6  8]
 [10 12]]

 Умножение на число:
 [[2 4]
 [6 8]]

 Перемножение матриц:
 [[19 22]
 [43 50]]

 Определитель: -2.0000000000000004

 Базисный минор:
 [[4]]

 det минора: 4.0

 Собственные векторы:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

 Собственные значения: [-0.37228132  5.37228132]

 Транспонирование:
 [[1 3]
 [2 4]]

 Обратная матрица:
 [[-2.   1. ]
 [ 1.5 -0.5]]

 SVD-разложение:
 (array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]]), array([5.4649857 , 0.36596619]), array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844]]))

 Псевдообратная матрица:
 [[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]


Умножение матрицы на вектор. Тут у x размерность (3,), а не (3,1).

Для x = np.array([...]) - ориентация строка/столбец не задается. Это просто 1-мерный вектор без ориентации.

In [10]:
A = np.array([[1,2,3],
              [4,5,6]])
print(A.shape)

x = np.array([7,8,9])
print(x.shape)

y = A @ x
print(y, y.shape)

(2, 3)
(3,)
[ 50 122] (2,)


NumPy не превращает буквально (3,) в (3,1). Он просто использует специальное правило для 1-мерных массивов. То есть (3,) — это вектор без ориентации.

Результат тоже вектор без ориентации (2,)

Если сделать настоящий столбец.

In [11]:
x = np.array([[7],
              [8],
              [9]])
print(x.shape)

y = A @ x
print(y, y.shape)

(3, 1)
[[ 50]
 [122]] (2, 1)


Вывод - столбец (2, 1).

А так задается вектор-строка.

In [12]:
x = np.array([[7,8,9]])
print(x.shape)

# или через reshape
x = np.array([7,8,9])
x_row = x.reshape(1,-1)
print(x_row.shape)

(1, 3)
(1, 3)


## 10. Статистика

In [13]:
data = np.array([1, 2, 3, 4, 5])

print("sum =", np.sum(data))
print("mean =", np.mean(data))
print("median =", np.median(data))
print("std =", np.std(data))
print("var =", np.var(data))
print("min =", np.min(data))
print("max =", np.max(data))
print("argmin =", np.argmin(data)) # индекс первого вхождения минимального значения в массиве
print("argmax =", np.argmax(data)) # индекс первого вхождения максимального значения в массиве

sum = 15
mean = 3.0
median = 3.0
std = 1.4142135623730951
var = 2.0
min = 1
max = 5
argmin = 0
argmax = 4


### Работа с размерностями (axis)

In [14]:
data = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
print("mean =", np.mean(data))          # по всей матрице
print("mean =", np.mean(data, axis=0))  # по столбцам
print("mean =", np.mean(data, axis=1))  # по строкам

mean = 4.5
mean = [2.5 3.5 4.5 5.5 6.5]
mean = [2. 7.]


### Нормализация признаков
$$X_{scaled} = \frac{X - \mu}{\sigma}$$


In [15]:
X = np.array([[1,200],[2,300],[3,400]])
X_scaled = (X - X.mean(axis=0)) / X.std(axis=0)
X_scaled

array([[-1.22474487, -1.22474487],
       [ 0.        ,  0.        ],
       [ 1.22474487,  1.22474487]])

### Центрирование данных

In [16]:
X = np.array([[1,200],[2,300],[3,400]])
X - np.mean(X, axis=0)

array([[  -1., -100.],
       [   0.,    0.],
       [   1.,  100.]])

## 11. NumPy в Machine Learning

![cosine_similarity](cosine_similarity.png)

### Эвклидово расстояние

In [17]:
v =np. array ([20, 40]) 
w =np. array ([30, 20])

d =np.linalg.norm(v-w)

print ("Эвклидово расстояние между векторами v и w: ", d)

Эвклидово расстояние между векторами v и w:  22.360679774997898


### Косинусное сходство

In [18]:
cos = np.dot(v,w)/(np.linalg.norm(v)*np.linalg.norm(w))
print("Cos угла:", cos)

Cos угла: 0.8682431421244591


### Softmax

In [19]:
def softmax(x):
    x = x - np.max(x)           # стабилизация (убираем максимум). Функция экспоненты растёт ОЧЕНЬ быстро:
                                # значения могут выйти за пределы типа float и превращаются в inf
                                # inf / inf → nan. Softmax ломается.
                                # Softmax зависит не от абсолютных значений, а от разницы между ними.
                                # Пожтому результат не меняется.


    exp_x = np.exp(x)           # экспонента
    return exp_x / np.sum(exp_x)  # нормализация

# пример
z = np.array([2.0, 1.0, 0.1])
probs = softmax(z)

print("Softmax:", probs)
print("Сумма:", np.sum(probs))

Softmax: [0.65900114 0.24243297 0.09856589]
Сумма: 1.0


### Softmax для батча (2D массив)

In [20]:
def softmax_batch(X):
    X = X - np.max(X, axis=1, keepdims=True)  # по строкам
    exp_X = np.exp(X)
    return exp_X / np.sum(exp_X, axis=1, keepdims=True)

# пример
X = np.array([[2.0, 1.0, 0.1],
              [1.0, 3.0, 0.2]])

print(softmax_batch(X))

[[0.65900114 0.24243297 0.09856589]
 [0.11314284 0.8360188  0.05083836]]


### Линейная регрессия (нормальное уравнение)
$$\theta = (X^T X)^{-1} X^T y$$


In [21]:
X = np.array([[1,1],[1,2],[1,3]])
y = np.array([1,2,3])

theta = np.linalg.inv(X.T @ X) @ X.T @ y
print("theta:", theta)

theta: [-1.77635684e-15  1.00000000e+00]
