# Конспект: Матрицы и определители

> Конспект сделан по учебнику: Линейная алгебра. Ильин В.А., Позняк Э.Г. Глава «Матрицы и определители».<br>
> Дополнен практическими примерами на Python/NumPy.

## 1. Понятие матрицы

**Матрица** — это прямоугольная таблица чисел (или элементов некоторого поля), содержащая *m* строк и *n* столбцов.  
Обычно матрицу обозначают большой буквой (например, $A$), а её элементы — $a_{ij}$, где:

- $i$ — номер строки,
- $j$ — номер столбца.

Пример матрицы размера $m\times n$:

$$
A = (a_{ij}) =
\begin{pmatrix}
a_{11} & a_{12} & \dots & a_{1n}\\
a_{21} & a_{22} & \dots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{m1} & a_{m2} & \dots & a_{mn}
\end{pmatrix}
$$


### 1.1 Порядок матрицы

**Порядок (размер) матрицы** — это пара чисел $(m,n)$ или запись $m\times n$.

- $m$ — число строк
- $n$ — число столбцов


### 1.2 Квадратные матрицы

Матрица называется **квадратной**, если число строк равно числу столбцов: $m=n$.  
Тогда говорят: «матрица *n-го порядка*» и пишут $A\in \mathbb{R}^{n\times n}$ (или над другим полем).


### 1.3 Элементы матрицы, строки и столбцы

- **Элемент матрицы** $a_{ij}$ — число на пересечении *i*-й строки и *j*-го столбца.
- **Строка** — набор элементов с фиксированным $i$: $(a_{i1}, a_{i2},\dots,a_{in})$.
- **Столбец** — набор элементов с фиксированным $j$: $(a_{1j}, a_{2j},\dots,a_{mj})^T$.


### 1.4 Главная и побочная диагональ (квадратная матрица)

Пусть $A$ — квадратная матрица порядка $n$.

- **Главная диагональ**: элементы $a_{11}, a_{22},\dots,a_{nn}$ (индексы совпадают).
- **Побочная диагональ**: элементы $a_{1n}, a_{2,n-1},\dots,a_{n1}$ (индексы в сумме дают $n+1$).


### 1.5 Диагональные и единичные матрицы

**Диагональная матрица** — квадратная матрица, у которой вне главной диагонали стоят нули:

$$
D=\operatorname{diag}(d_1,\dots,d_n)=
\begin{pmatrix}
d_1 & 0 & \dots & 0\\
0 & d_2 & \dots & 0\\
\vdots & \vdots & \ddots & \vdots\\
0 & 0 & \dots & d_n
\end{pmatrix}
$$

**Единичная матрица** $E$ — это диагональная матрица с $d_1=\dots=d_n=1$.  
Она играет роль «единицы» для умножения матриц: $AE=EA=A$.


## 2. Основные операции с матрицами и их свойства


### 2.1 Сложение матриц

Складывать можно только матрицы одинакового размера $m\times n$.  
Если $C=A+B$, то:

$$
c_{ij}=a_{ij}+b_{ij}
$$

**Свойства сложения:**
- коммутативность: $A+B=B+A$
- ассоциативность: $(A+B)+C=A+(B+C)$
- существует нулевая матрица $0$: $A+0=A$
- существует противоположная матрица $-A$: $A+(-A)=0$


### 2.2 Умножение матрицы на число

Если $\lambda$ — число (скаляр), то $C=\lambda A$ определяется поэлементно:

$$
c_{ij}=\lambda a_{ij}
$$

**Свойства:**
- $(\lambda+\mu)A=\lambda A+\mu A$
- $\lambda(A+B)=\lambda A+\lambda B$
- $(\lambda\mu)A=\lambda(\mu A)$


### 2.3 Произведение матриц

Пусть $A$ размера $m\times n$, а $B$ размера $n\times p$. Тогда произведение $C=AB$ имеет размер $m\times p$, и

$$
c_{ij}=\sum_{k=1}^{n} a_{ik}b_{kj}
$$

**Важно:** произведение определено только если число столбцов $A$ равно числу строк $B$.

**Свойства:**
- ассоциативность: $(AB)C=A(BC)$
- дистрибутивность: $A(B+C)=AB+AC$, $(A+B)C=AC+BC$
- умножение в общем случае **не коммутативно**: обычно $AB\ne BA$


In [1]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("A=")
print(A)
print("\nB=")
print(B)

print("\nA+B=")
print(A+B)

print("\n2*A=")
print(2*A)

print("\nA@B=")
print(A@B)

print("\nB@A=")
print(B@A)


A=
[[1 2]
 [3 4]]

B=
[[5 6]
 [7 8]]

A+B=
[[ 6  8]
 [10 12]]

2*A=
[[2 4]
 [6 8]]

A@B=
[[19 22]
 [43 50]]

B@A=
[[23 34]
 [31 46]]


In [2]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

print("\nA@B=")
print(A@B)


A@B=
[[ 58  64]
 [139 154]]


Число столбцов $A$ равно числу строк $B$.<br>
Результирующая матрица имеет число строк равное числу строк $A$ и число столбцов равное числу столбцов $B$.

## 3. Ранг матрицы

**Ранг матрицы** $\operatorname{rank}(A)$ — это:
- максимальное число линейно независимых строк (или столбцов) матрицы;
- то же самое: размерность пространства, натянутого на строки (или столбцы).

Эквивалентно через миноры:
- ранг равен наибольшему порядку ненулевого минора матрицы.

Интуитивно ранг показывает «сколько независимой информации» содержит матрица.


In [3]:
# Пример ранга в NumPy
import numpy as np

A = np.array([[1, 2, 3],
              [2, 4, 6],
              [1, 1, 1]])

print("A=")
print(A)
print("rank(A) =", np.linalg.matrix_rank(A))


A=
[[1 2 3]
 [2 4 6]
 [1 1 1]]
rank(A) = 2


## 4. Определители

Формула определителя построена так, чтобы выполнялись свойства:
- Линейность по каждой строке
- Меняет знак при перестановке строк
- Для единичной матрицы равен 1
Функция, обладающая этими свойствами, как раз и есть определитель.

Определитель (детерминант) определён для **квадратных** матриц.

### 4.1 Определитель 1-го и 2-го порядка

Для $1\times 1$ матрицы $[a_{11}]$:  
$$
\det[a_{11}] = a_{11}
$$

Для $2\times 2$ матрицы
$$
A=
\begin{pmatrix}
a_{11} & a_{12}\\
a_{21} & a_{22}
\end{pmatrix}
$$
определитель:
$$
\det(A)=a_{11}a_{22}-a_{12}a_{21}
$$


### 4.2 Миноры, алгебраические дополнения и разложение Лапласа

- **Минор** $M_{ij}$ элемента $a_{ij}$ — это определитель матрицы порядка $n-1$, полученной вычеркиванием *i*-й строки и *j*-го столбца.
- **Алгебраическое дополнение** (кофактор) $A_{ij}$:
$$
A_{ij}=(-1)^{i+j}M_{ij}
$$

**Разложение (формула Лапласа) по i-й строке:**
$$
\det(A)=\sum_{j=1}^{n} a_{ij}A_{ij}
$$

Аналогично по j-му столбцу:
$$
\det(A)=\sum_{i=1}^{n} a_{ij}A_{ij}
$$


In [4]:
# Функции для учебных вычислений детерминанта через разложение Лапласа (рекурсивно).
# Для больших n это медленно, но для n<=5 подходит как учебный пример.

import numpy as np

def det_laplace(A: np.ndarray) -> float:
    A = np.asarray(A, dtype=float)
    n = A.shape[0]
    assert A.shape == (n, n)
    if n == 1:
        return A[0, 0]
    if n == 2:
        return A[0,0]*A[1,1] - A[0,1]*A[1,0]
    # разложение по первой строке
    total = 0.0
    for j in range(n):
        minor = np.delete(np.delete(A, 0, axis=0), j, axis=1)
        total += ((-1)**(1+(j+1))) * A[0, j] * det_laplace(minor)
    return total

A = np.array([[2, 1, 3],
              [0, 4, 5],
              [7, 2, 1]], dtype=float)

print("A=")
print(A)
print("det(A) via Laplace =", det_laplace(A))
print("det(A) via numpy   =", np.linalg.det(A))


A=
[[2. 1. 3.]
 [0. 4. 5.]
 [7. 2. 1.]]
det(A) via Laplace = -61.0
det(A) via numpy   = -61.00000000000001


## 5. Свойства определителей (кратко)

Ниже — базовые свойства, которые активно используются при вычислениях:

1) Перестановка двух строк (или двух столбцов) меняет знак определителя:  
$$
\det(\dots, r_i, \dots, r_j, \dots) = -\det(\dots, r_j, \dots, r_i, \dots)
$$

2) Если две строки (или два столбца) совпадают, то определитель равен нулю.

3) Если все элементы некоторой строки (или столбца) равны нулю, то определитель равен нулю.

4) Умножение строки на число $\lambda$ умножает определитель на $\lambda$.

5) Прибавление к строке линейной комбинации других строк **не меняет** определитель  
(аналогично для столбцов).

6) Для треугольной матрицы (верхнетреугольной или нижнетреугольной) определитель равен произведению элементов главной диагонали:
$$
\det(T)=\prod_{i=1}^{n} t_{ii}
$$


In [5]:
# Демонстрация свойств определителя на примерах
import numpy as np

A = np.array([[1., 2., 3.],
              [4., 5., 6.],
              [7., 8., 10.]])

detA = np.linalg.det(A)

# 1) переставим две строки
B = A.copy()
B[[0,1]] = B[[1,0]]
detB = np.linalg.det(B)

print("det(A) =", detA)
print("det(B) =", detB, " (должно быть -det(A))")

# 4) умножим строку на 3
C = A.copy()
C[0] *= 3
detC = np.linalg.det(C)
print("det(C) =", detC, " (должно быть 3*det(A))")

# 5) прибавим к строке линейную комбинацию других строк
D = A.copy()
D[0] = D[0] + 2*D[1]   # r1 <- r1 + 2*r2
detD = np.linalg.det(D)
print("det(D) =", detD, " (должно быть det(A))")


det(A) = -2.9999999999999996
det(B) = 2.9999999999999996  (должно быть -det(A))
det(C) = -8.999999999999998  (должно быть 3*det(A))
det(D) = -2.999999999999998  (должно быть det(A))


## 6. Примеры вычисления определителей

### 6.1 Определитель 2×2
$$
\begin{vmatrix}
3 & -1\\
2 & 5
\end{vmatrix}
= 3\cdot 5 - (-1)\cdot 2 = 15+2=17
$$


### 6.2 Определитель 3×3 разложением по строке

$$
A=
\begin{pmatrix}
2 & 1 & 3\\
0 & 4 & 5\\
7 & 2 & 1
\end{pmatrix}
$$

Разложим по первой строке:
$$
\det(A)=2A_{11}+1A_{12}+3A_{13}
$$
где $A_{1j}=(-1)^{1+j}M_{1j}$, а $M_{1j}$ — соответствующие миноры (2×2).


In [6]:
# Посчитаем этот же детерминант вручную через миноры 2×2 (для наглядности)
import numpy as np

A = np.array([[2, 1, 3],
              [0, 4, 5],
              [7, 2, 1]], dtype=float)

def minor_1j(A, j):
    # вычеркиваем 1-ю строку и j-й столбец (j: 0..n-1)
    return np.delete(np.delete(A, 0, axis=0), j, axis=1)

det = 0
for j in range(3):
    M = minor_1j(A, j)
    cof = ((-1)**(1+(j+1))) * np.linalg.det(M)
    det += A[0, j] * cof
    print(f"j={j+1}: a_1{j+1}={A[0,j]:g}, \nminor=\n{M}, \ncofactor={cof:g} \n")

print("det(A) =", det)

j=1: a_11=2, 
minor=
[[4. 5.]
 [2. 1.]], 
cofactor=-6 

j=2: a_12=1, 
minor=
[[0. 5.]
 [7. 1.]], 
cofactor=35 

j=3: a_13=3, 
minor=
[[0. 4.]
 [7. 2.]], 
cofactor=-28 

det(A) = -60.99999999999999


## 7. Базисный минор

### 7.1 Минор порядка k

**Минор порядка $k$** матрицы $A$ — это определитель $k\times k$, полученный выбором любых $k$ строк и $k$ столбцов.

### 7.2 Базисный минор (идея)

Пусть ранг матрицы $A$ равен $r$. Тогда существует ненулевой минор порядка $r$, и все миноры порядка больше $r$ равны нулю.

Ненулевой минор порядка $r$, «опирающийся» на линейно независимые строки/столбцы, называют **базисным минором** (в учебнике доказывается теорема о базисном миноре: через него выражаются остальные строки/столбцы, а также удобно видеть связь ранга и миноров).


In [7]:
# Практическая иллюстрация: находим ранг и пример ненулевого минора максимального порядка.

import numpy as np
import itertools

A = np.array([[1, 2, 3, 4],
              [2, 4, 6, 8],
              [0, 1, 1, 1],
              [1, 3, 4, 5]], dtype=float)

r = np.linalg.matrix_rank(A)
print("rank(A) =", r)

def find_nonzero_minor(A, k, tol=1e-9):
    n, m = A.shape
    for rows in itertools.combinations(range(n), k):
        for cols in itertools.combinations(range(m), k):
            M = A[np.ix_(rows, cols)]
            d = np.linalg.det(M)
            if abs(d) > tol:
                return rows, cols, d, M
    return None

res = find_nonzero_minor(A, r)
rows, cols, d, M = res
print("Пример ненулевого минора порядка r:")
print("rows =", rows, "cols =", cols)
print("minor matrix =\n", M)
print("det(minor) =", d)


rank(A) = 2
Пример ненулевого минора порядка r:
rows = (0, 2) cols = (0, 1)
minor matrix =
 [[1. 2.]
 [0. 1.]]
det(minor) = 1.0


## 8. Мини-шпаргалка

- Матрица $m\times n$ — таблица элементов $a_{ij}$.
- Главная диагональ: $a_{11}, a_{22},\dots,a_{nn}$.
- Единичная матрица $E$: на диагонали 1, вне диагонали 0.
- Диагональная матрица: вне диагонали нули.
- Произведение матриц: $c_{ij}=\sum_k a_{ik}b_{kj}$.
- Определитель 2×2: $a_{11}a_{22}-a_{12}a_{21}$.
- Разложение Лапласа: $\det(A)=\sum a_{ij}A_{ij}$.
- Ранг = наибольший порядок ненулевого минора.
